using System;
using System.Drawing;
using System.IO;
using System.Diagnostics;
using System.Threading;
using System.Threading.Tasks;
using System.Windows.Forms;
namespace Astra {
sealed class Surface:Panel {
 public Color BorderColor=Color.FromArgb(192,206,216);
 public Surface(){DoubleBuffered=true;ResizeRedraw=true;BackColor=Color.White;Padding=new Padding(14,10,14,10);}
 protected override void OnPaint(PaintEventArgs e){base.OnPaint(e);if(Width>3&&Height>3)using(var pen=new Pen(BorderColor))e.Graphics.DrawRectangle(pen,1,1,Width-3,Height-3);}
}
sealed class Gui:Form {
 static readonly Color Ink=Color.FromArgb(29,47,62),Muted=Color.FromArgb(105,122,137),Accent=Color.FromArgb(18,113,103);
 readonly ComboBox chain=new ThemeComboBox(),mode=new ThemeComboBox(),chars=new ThemeComboBox(),format=new ThemeComboBox();
 readonly TextBox prefix=new TextBox(),suffix=new TextBox(),folder=new TextBox(),logs=new TextBox();
 readonly NumericUpDown repeat=new NumericUpDown(),count=new NumericUpDown(),seconds=new NumericUpDown();
 readonly CheckBox sensitive=new ThemeCheckBox(),append=new ThemeCheckBox();
 readonly Button start=new ThemeButton(),stop=new ThemeButton(),test=new ThemeButton(),browse=new ThemeButton(),open=new ThemeButton(),logButton=new ThemeButton();
 readonly Label preview=new Label(),device=new Label(),hardware=new Label(),configuration=new Label(),ruleHelp=new Label(),exportHelp=new Label(),speedValue=new Label(),savedValue=new Label(),elapsedValue=new Label(),status=new Label();
 readonly Surface rulesCard=new Surface(),outputCard=new Surface();readonly ToolTip tips=new ToolTip();
 Palette palette=Palette.SystemPalette();
 CancellationTokenSource cancel;bool closing,busy,ready;Form logWindow;
 public static int Run(){Application.EnableVisualStyles();Application.SetCompatibleTextRenderingDefault(false);Application.Run(new Gui());return 0;}
 public Gui(){
  Text="Astra v1.1.0";Font=new Font("Segoe UI",9F);ForeColor=Ink;BackColor=Color.FromArgb(243,246,249);AutoScaleDimensions=new SizeF(96,96);AutoScaleMode=AutoScaleMode.Dpi;
  ClientSize=new Size(820,588);FormBorderStyle=FormBorderStyle.FixedSingle;MaximizeBox=false;SizeGripStyle=SizeGripStyle.Hide;StartPosition=FormStartPosition.CenterScreen;DoubleBuffered=true;
  var root=Grid(1,6);root.Padding=new Padding(14);root.Dock=DockStyle.Fill;int[] heights={78,286,44,80,36,36};for(int i=0;i<heights.Length;i++)root.RowStyles.Add(new RowStyle(SizeType.Absolute,heights[i]));Controls.Add(root);
  var gpuCard=new Surface{Dock=DockStyle.Fill,Margin=new Padding(0,0,0,8),Padding=new Padding(14,6,14,6)};var gpu=Grid(1,3);gpu.Dock=DockStyle.Fill;gpu.RowStyles.Add(new RowStyle(SizeType.Absolute,23));gpu.RowStyles.Add(new RowStyle(SizeType.Absolute,19));gpu.RowStyles.Add(new RowStyle(SizeType.Percent,100));Style(device,11,Ink,true);Style(hardware,9,Muted,false);Style(configuration,8.5F,Muted,false);device.Text="Detecting NVIDIA GPU…";hardware.Text="Hardware is detected at startup only.";configuration.Text="Search: 256 independent random groups × 64 batch";var gpuHeader=Grid(2,1);gpuHeader.Dock=DockStyle.Fill;gpuHeader.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100));gpuHeader.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,185));gpuHeader.Controls.Add(device,0,0);var badge=Label("ETH · TRON · POLYGON",8.5F,Accent,true);badge.TextAlign=ContentAlignment.MiddleRight;gpuHeader.Controls.Add(badge,1,0);gpu.Controls.Add(gpuHeader,0,0);gpu.Controls.Add(hardware,0,1);gpu.Controls.Add(configuration,0,2);gpuCard.Controls.Add(gpu);root.Controls.Add(gpuCard,0,0);
  var body=Grid(3,1);body.Dock=DockStyle.Fill;body.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,55));body.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,10));body.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,45));rulesCard.Dock=outputCard.Dock=DockStyle.Fill;rulesCard.Margin=outputCard.Margin=Padding.Empty;body.Controls.Add(rulesCard,0,0);body.Controls.Add(outputCard,2,0);root.Controls.Add(body,0,1);
  SetupInputs();BuildRules();BuildOutput();
  Style(preview,9,Accent,false);preview.Margin=new Padding(2,5,2,2);root.Controls.Add(preview,0,2);
  var metrics=Grid(3,1);metrics.Dock=DockStyle.Fill;for(int i=0;i<3;i++)metrics.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100F/3));metrics.Controls.Add(Metric("Search · million candidates/s",speedValue,"— M/s"),0,0);metrics.Controls.Add(Metric("Flushed · includes Excel staging",savedValue,"0"),1,0);metrics.Controls.Add(Metric("Elapsed time",elapsedValue,"00:00:00"),2,0);root.Controls.Add(metrics,0,3);
  Style(status,8.5F,Muted,false);status.Margin=new Padding(2,2,2,2);status.Text="Start when ready. ETA is a probability estimate, not a countdown.";root.Controls.Add(status,0,4);
  var actions=new FlowLayoutPanel{Dock=DockStyle.Fill,WrapContents=false,Margin=Padding.Empty};Button(start,"Start",122,true);Button(stop,"Stop and save",112,false);Button(open,"Open folder",126,false);Button(logButton,"Logs",88,false);Button(test,"Self-test",90,false);foreach(var b in new[]{start,stop,open,logButton,test})actions.Controls.Add(b);root.Controls.Add(actions,0,5);start.Enabled=stop.Enabled=false;
  logs.Multiline=true;logs.ReadOnly=true;logs.ScrollBars=ScrollBars.Both;logs.WordWrap=false;logs.Dock=DockStyle.Fill;logs.Font=new Font("Segoe UI",9);logs.BackColor=Color.White;
  foreach(var box in new[]{prefix,suffix})box.TextChanged+=(s,e)=>Preview();chain.SelectedIndexChanged+=(s,e)=>Preview();mode.SelectedIndexChanged+=(s,e)=>Preview();chars.TextChanged+=(s,e)=>Preview();repeat.ValueChanged+=(s,e)=>Preview();sensitive.CheckedChanged+=(s,e)=>Preview();format.SelectedIndexChanged+=(s,e)=>{if(format.SelectedIndex!=0)append.Checked=false;Preview();};append.CheckedChanged+=(s,e)=>Preview();
  browse.Click+=(s,e)=>{using(var d=new FolderBrowserDialog{Description="Choose a folder for TXT / Excel. Files are named automatically.",SelectedPath=Directory.Exists(folder.Text)?folder.Text:DesktopFolder,ShowNewFolderButton=true})if(d.ShowDialog(this)==DialogResult.OK)folder.Text=d.SelectedPath;};
  open.Click+=(s,e)=>{try{string path=Path.GetFullPath(folder.Text);if(!Directory.Exists(path))throw new IOException("Folder does not exist.");Process.Start(new ProcessStartInfo("explorer.exe","\""+path+"\""){UseShellExecute=true});}catch(Exception ex){Notice(ex.Message);}};
  logButton.Click+=(s,e)=>ShowLogs();start.Click+=async(s,e)=>await StartSearch();stop.Click+=(s,e)=>RequestStop();test.Click+=async(s,e)=>await Test();
  FormClosing+=(s,e)=>{if(busy){e.Cancel=true;closing=true;RequestStop();}};Shown+=async(s,e)=>await DetectHardware();Microsoft.Win32.SystemEvents.UserPreferenceChanged+=PreferenceChanged;FormClosed+=(s,e)=>{Microsoft.Win32.SystemEvents.UserPreferenceChanged-=PreferenceChanged;tips.Dispose();};Preview();ApplyPalette(palette);
 }
 public static string DesktopFolder {get{return Environment.GetFolderPath(Environment.SpecialFolder.DesktopDirectory);}}
 void PreferenceChanged(object sender,Microsoft.Win32.UserPreferenceChangedEventArgs e){UI(()=>{ApplyPalette(Palette.SystemPalette());Preview();});}
 protected override void OnHandleCreated(EventArgs e){base.OnHandleCreated(e);ApplyPalette(Palette.SystemPalette());}
 protected override void WndProc(ref Message m){base.WndProc(ref m);if(m.Msg==0x001A||m.Msg==0x031A)UI(()=>{ApplyPalette(Palette.SystemPalette());Preview();});}
 internal void ApplyPalette(Palette value){palette=value;SuspendLayout();PaintControls(this,value);WindowTheme.Caption(this,value);tips.BackColor=value.Card;tips.ForeColor=value.Text;if(logWindow!=null&&!logWindow.IsDisposed){PaintControls(logWindow,value);WindowTheme.Caption(logWindow,value);}ResumeLayout(false);Invalidate(true);}
 static void PaintControls(Control c,Palette t){
  var surface=c as Surface;var button=c as Button;var label=c as Label;var combo=c as ComboBox;
  if(c is Form){c.BackColor=t.Window;c.ForeColor=t.Text;}
  else if(surface!=null){surface.BackColor=t.Card;surface.BorderColor=t.Border;}
  else if(button!=null){bool primary=Equals(button.Tag,"primary");button.BackColor=primary?Color.FromArgb(18,113,103):t.Button;button.ForeColor=primary?Color.White:t.Text;button.FlatAppearance.BorderColor=t.Border;button.FlatAppearance.MouseOverBackColor=primary?Color.FromArgb(24,134,121):t.Hover;button.FlatAppearance.MouseDownBackColor=t.Hover;}
  else if(c is TextBoxBase||c is NumericUpDown||combo!=null){c.BackColor=c.Enabled?t.Input:t.Card;c.ForeColor=c.Enabled?t.Text:t.Disabled;if(combo!=null)combo.FlatStyle=FlatStyle.Flat;WindowTheme.Input(c,t);}
  else {c.BackColor=c.Parent==null?t.Window:c.Parent.BackColor;c.ForeColor=t.TextColor(c.Tag);}
  if(label!=null)label.ForeColor=t.TextColor(label.Tag);
  var themedButton=c as ThemeButton;if(themedButton!=null)themedButton.Colors=t;
  var themedCheck=c as ThemeCheckBox;if(themedCheck!=null)themedCheck.Colors=t;
  var themedCombo=c as ThemeComboBox;if(themedCombo!=null)themedCombo.Colors=t;
  foreach(Control child in c.Controls)PaintControls(child,t);c.Invalidate();
 }
 static TableLayoutPanel Grid(int columns,int rows){var grid=new TableLayoutPanel{ColumnCount=columns,RowCount=rows,Margin=Padding.Empty,Padding=Padding.Empty};if(rows==1)grid.RowStyles.Add(new RowStyle(SizeType.Percent,100));if(columns==1)grid.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100));return grid;}
 static Label Label(string text,float size,Color color,bool bold){var l=new Label{Text=text};Style(l,size,color,bold);return l;}
 static void Style(Label l,float size,Color color,bool bold){l.Font=new Font("Segoe UI",size,bold?FontStyle.Bold:FontStyle.Regular);l.Tag=color==Muted?TextTone.Muted:color==Accent?TextTone.Accent:color==Color.FromArgb(142,93,30)?TextTone.Warning:TextTone.Main;l.ForeColor=color;l.Dock=DockStyle.Fill;l.TextAlign=ContentAlignment.MiddleLeft;l.AutoEllipsis=true;l.Margin=Padding.Empty;}
 static void Button(Button b,string text,int width,bool primary){b.Tag=primary?"primary":"secondary";b.UseVisualStyleBackColor=false;b.Text=text;b.Width=width;b.Height=32;b.Margin=new Padding(0,0,8,0);b.FlatStyle=FlatStyle.Flat;b.FlatAppearance.BorderSize=primary?0:1;b.FlatAppearance.BorderColor=Color.FromArgb(210,221,228);b.BackColor=primary?Accent:Color.White;b.ForeColor=primary?Color.White:Ink;b.Cursor=Cursors.Hand;}
 void SetupInputs(){
  chain.DropDownStyle=mode.DropDownStyle=format.DropDownStyle=ComboBoxStyle.DropDownList;
  chain.Items.AddRange(new object[]{"Ethereum / ETH · Mainnet","TRON / TRX · Mainnet","Polygon PoS / POL · 137"});chain.SelectedIndex=0;
  mode.Items.AddRange(new object[]{"Fixed prefix / suffix","Repeated suffix"});mode.SelectedIndex=1;
  chars.Items.AddRange(new object[]{"All valid characters","Digits only","Letters only","Lowercase only","Uppercase only"});chars.DropDownStyle=ComboBoxStyle.DropDown;chars.SelectedIndex=0;
  format.Items.AddRange(new object[]{"TXT text","Excel workbook (.xlsx)","TXT + Excel"});format.SelectedIndex=2;
  repeat.Minimum=1;repeat.Maximum=40;repeat.Value=6;count.Maximum=1000000000;count.Value=1;seconds.Maximum=315360000;
  sensitive.Text="Match case";sensitive.AutoSize=true;sensitive.Dock=DockStyle.Right;sensitive.Margin=Padding.Empty;append.Text="Append to this network's TXT file";append.AutoSize=true;append.Margin=Padding.Empty;append.Tag=TextTone.Muted;append.ForeColor=Muted;
  folder.Text=DesktopFolder;folder.AccessibleName="Output folder";
  tips.SetToolTip(prefix,"Omit the fixed T or 0x. Leave empty for any prefix.");tips.SetToolTip(suffix,"Fixed prefix and suffix must both match. Leave empty for any suffix.");tips.SetToolTip(chars,"Presets filter invalid characters. Type a custom set such as 58aB. ETH / Polygon accept hexadecimal characters only.");tips.SetToolTip(sensitive,"Checked: match actual output case. Unchecked: aAaA counts as a four-character repeat. Checked: only aaaa or AAAA.");tips.SetToolTip(append,"Writes tron_results.txt / eth_results.txt / polygon_results.txt; appends if present. Every task uses fresh random seeds.");
 }
 Control Input(string title,Control c){var g=Grid(1,2);g.Dock=DockStyle.Fill;g.RowStyles.Add(new RowStyle(SizeType.Absolute,22));g.RowStyles.Add(new RowStyle(SizeType.Percent,100));g.Controls.Add(Label(title,8.5F,Muted,false),0,0);c.Dock=DockStyle.Top;c.Margin=new Padding(0,0,0,1);c.AccessibleName=title;g.Controls.Add(c,0,1);return g;}
 Control Pair(Control a,Control b){var g=Grid(3,1);g.Dock=DockStyle.Fill;g.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,50));g.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,12));g.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,50));g.Controls.Add(a,0,0);g.Controls.Add(b,2,0);return g;}
 void BuildRules(){var g=Grid(1,6);g.Dock=DockStyle.Fill;int[] h={24,46,46,46,46,1};for(int i=0;i<6;i++)g.RowStyles.Add(new RowStyle(i==5?SizeType.Percent:SizeType.Absolute,i==5?100:h[i]));var head=Grid(2,1);head.Dock=DockStyle.Fill;head.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,60));head.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,40));head.Controls.Add(Label("01  Match rules",11,Ink,true),0,0);head.Controls.Add(sensitive,1,0);g.Controls.Add(head,0,0);g.Controls.Add(Input("Network",chain),0,1);g.Controls.Add(Input("Suffix mode",mode),0,2);g.Controls.Add(Pair(Input("Prefix · optional",prefix),Input("Suffix · optional",suffix)),0,3);g.Controls.Add(Pair(Input("Repeat length",repeat),Input("Characters · editable",chars)),0,4);Style(ruleHelp,8.5F,Muted,false);ruleHelp.Padding=new Padding(0,2,0,0);g.Controls.Add(ruleHelp,0,5);rulesCard.Controls.Add(g);}
 void BuildOutput(){var g=Grid(1,8);g.Dock=DockStyle.Fill;int[] h={24,20,34,20,46,46,22,1};for(int i=0;i<8;i++)g.RowStyles.Add(new RowStyle(i==7?SizeType.Percent:SizeType.Absolute,i==7?100:h[i]));g.Controls.Add(Label("02  Output / limits",11,Ink,true),0,0);g.Controls.Add(Label("Output folder",8.5F,Muted,false),0,1);var path=Grid(2,1);path.Dock=DockStyle.Fill;path.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100));path.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,88));folder.Dock=DockStyle.None;folder.Anchor=AnchorStyles.Left|AnchorStyles.Right;folder.Margin=new Padding(0,0,8,0);path.Controls.Add(folder,0,0);Button(browse,"Browse…",88,false);browse.Dock=DockStyle.None;browse.Anchor=AnchorStyles.Left|AnchorStyles.Right;browse.Height=30;browse.Margin=Padding.Empty;path.Controls.Add(browse,1,0);g.Controls.Add(path,0,2);g.Controls.Add(Label("Automatic filenames; existing results are kept.",8,Muted,false),0,3);g.Controls.Add(Input("Output format",format),0,4);g.Controls.Add(Pair(Input("Count · 0 = unlimited",count),Input("Seconds · 0 = unlimited",seconds)),0,5);g.Controls.Add(append,0,6);Style(exportHelp,8F,Color.FromArgb(142,93,30),false);g.Controls.Add(exportHelp,0,7);outputCard.Controls.Add(g);}
 Control Metric(string caption,Label value,string initial){var card=new Surface{Dock=DockStyle.Fill,Margin=new Padding(0,0,value==elapsedValue?0:8,0),Padding=new Padding(12,8,12,8)};var g=Grid(1,2);g.Dock=DockStyle.Fill;g.RowStyles.Add(new RowStyle(SizeType.Absolute,20));g.RowStyles.Add(new RowStyle(SizeType.Percent,100));g.Controls.Add(Label(caption,8,Muted,false),0,0);Style(value,18,Ink,true);value.Text=initial;g.Controls.Add(value,0,1);card.Controls.Add(g);return card;}
 Options Read(){string[] c={"all","digits","letters","lower","upper"};return new Options{Rule=new Rules{Chain=chain.SelectedIndex==0?"eth":chain.SelectedIndex==1?"tron":"polygon",Prefix=prefix.Text.Trim(),Suffix=mode.SelectedIndex==0?suffix.Text.Trim():"",Repeat=mode.SelectedIndex==1?(int)repeat.Value:0,CharChoice=chars.SelectedIndex>=0?c[chars.SelectedIndex]:chars.Text.Trim(),Sensitive=sensitive.Checked},Count=(long)count.Value,Seconds=(double)seconds.Value,OutputDirectory=folder.Text.Trim(),Format=format.SelectedIndex==0?"txt":format.SelectedIndex==1?"xlsx":"both",Append=append.Checked};}
 void Preview(){bool rep=mode.SelectedIndex==1;suffix.Enabled=!rep;repeat.Enabled=chars.Enabled=rep;append.Enabled=format.SelectedIndex==0;ruleHelp.Text="Omit "+(chain.SelectedIndex==1?"T":"0x")+" from prefix; empty = any."+(rep?"\nExample: "+new string('8',(int)Math.Min(repeat.Value,8))+"; longer repeats also match.":"\nIf both are set, prefix and suffix must both match.");exportHelp.Text=format.SelectedIndex==0?"TXT contains plaintext private keys. Store offline.":"Plaintext private keys. XLSX every 5s / 10k rows; stop completes export.";try{var r=Read().Rule;r.Validate();preview.Tag=TextTone.Accent;preview.ForeColor=palette.Accent;preview.Text="Targets  "+(r.Prefix.Length>0?"prefix "+r.Prefix+"  ·  ":"")+(rep?"last "+r.Repeat+" identical  ·  "+r.Characters:"suffix "+(r.Suffix.Length>0?r.Suffix:"unlimited"))+"\n"+(r.Sensitive?"Match actual output case":"Case-insensitive comparison; checksum format is preserved");}catch(Exception ex){preview.Tag=TextTone.Error;preview.ForeColor=palette.Error;preview.Text=ex.Message;}}
 async Task DetectHardware(){try{var info=await Task.Run(()=>Cuda.Hardware());device.Text=info[0];hardware.Text=info[1];configuration.Text=info[2]+"   ·   256 groups × 64 batch";tips.SetToolTip(configuration,configuration.Text+". CPU affects seeding and verification; GPU and batch affect search throughput.");ready=true;start.Enabled=!busy;status.Text="GPU ready · CPU verified · One result per group · Fresh seeds for every task";}catch(Exception ex){device.Text="No usable NVIDIA CUDA GPU detected";hardware.Text=ex.Message;configuration.Text="Check the NVIDIA driver.";ready=false;Log(ex.Message);}}
 void UI(Action a){if(!IsDisposed&&IsHandleCreated)try{BeginInvoke(a);}catch(InvalidOperationException){}}
 void Log(string text){UI(()=>{if(logs.TextLength>40000)logs.Text=logs.Text.Substring(logs.TextLength-20000);logs.AppendText(text+Environment.NewLine);});}
 void Notice(string text){MessageBox.Show(this,text,"Astra v1.1.0",MessageBoxButtons.OK,MessageBoxIcon.Warning);}
 void ShowLogs(){if(logWindow==null||logWindow.IsDisposed){logWindow=new Form{Text="Astra v1.1.0 · Logs (no private keys)",ClientSize=new Size(760,340),StartPosition=FormStartPosition.CenterParent,Font=Font};logWindow.Controls.Add(logs);logWindow.FormClosing+=(s,e)=>{if(e.CloseReason==CloseReason.UserClosing){e.Cancel=true;logWindow.Hide();}};}PaintControls(logWindow,palette);logWindow.Show(this);WindowTheme.Caption(logWindow,palette);logWindow.BringToFront();}
 void Busy(bool value){busy=value;rulesCard.Enabled=outputCard.Enabled=!value;start.Enabled=!value&&ready;test.Enabled=!value;stop.Enabled=value&&cancel!=null;ApplyPalette(palette);}
 void RequestStop(){if(cancel!=null){cancel.Cancel();stop.Enabled=false;status.Text="Completing verification, flush and Excel export…";}else if(busy)status.Text="Completing self-test, then closing…";}
 async Task Test(){Busy(true);status.Text="Running extended self-test…";try{await Task.Run(()=>SelfTest.Run(true,Log));status.Text="Self-test passed · Addresses, case and GPU / CPU results agree";}catch(Exception ex){status.Text="Self-test failed: "+ex.Message;Log(status.Text);}finally{Busy(false);if(closing)Close();}}
 async Task StartSearch(){Options o;try{o=Read();o.Validate();}catch(Exception ex){Notice(ex.Message);return;}cancel=new CancellationTokenSource();Busy(true);speedValue.Text="— M/s";savedValue.Text="0";elapsedValue.Text="00:00:00";status.Text="Running startup checks and seeding…";try{await Task.Run(()=>Engine.Run(o,cancel.Token,s=>{string speed=(s.Rate/1e6).ToString("F2")+" M/s",saved=s.Saved.ToString("N0")+(s.Target>0?" / "+s.Target:""),elapsed=TimeSpan.FromSeconds(s.Elapsed).ToString(@"hh\:mm\:ss");double factor=s.Probability*s.GroupCandidates<1e-6?s.Probability:(1-Math.Pow(1-s.Probability,s.GroupCandidates))/s.GroupCandidates;double mean=s.Rate>0?1/(s.Rate*factor):double.PositiveInfinity;string summary=s.Stage+" · Mean delivery≈"+Snapshot.Duration(mean)+" · Remaining≈"+(s.Target==0?"unlimited":Snapshot.Duration(mean*Math.Max(0,s.Target-s.Accepted)))+" · GPU "+s.LastKernelMs.ToString("F1")+" ms";UI(()=>{speedValue.Text=speed;savedValue.Text=saved;elapsedValue.Text=elapsed;status.Text=summary;});},Log));}catch(Exception ex){Log("Stopped: "+ex.Message);status.Text="Error: "+ex.Message;Notice(ex.Message);}finally{cancel.Dispose();cancel=null;Busy(false);if(closing)Close();}}
}
}
